language: csharp
solution: Textile.sln
script:
  - xbuild /p:Configuration=Debug Textile.sln
  - mono ./packages/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./Textile.Test/bin/Debug/Textile.Test.dll